version: "3.9"

services:
  tweetky:
    build:
      context: .
    container_name: tweetky
    depends_on:
      - whatsapp
      - warproxy
    environment:
      - WHATSAPP_API_URL=http://whatsapp:3000
      - WHATSAPP_BASIC_AUTH=admin:admin
      - WARP_PROXY_URL=socks5://admin:admin@warproxy:8008
      - PYTHONUNBUFFERED=1
    volumes:
      - tweetky-data:/app/data
    working_dir: /app
    command: python main.py

  whatsapp:
    image: zlenner/go-whatsapp-web-multidevice-ipv6:latest
    container_name: whatsapp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - whatsapp-data:/app/storages
    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --os=Chrome
      - --account-validation=false
  warproxy:
    container_name: docker-warproxy
    image: zlenner/docker-warproxy-ipv6:latest
    restart: always
    volumes:
      - warp-config:/config
    ports:
      - 1356:${PROXY_PORT:-8008}
    environment:
      - PROXY_USER=admin
      - PROXY_PASS=admin
      - WGCF_LICENSE_KEY=${WGCF_LICENSE_KEY}

volumes:
  whatsapp-data:
  tweetky-data:
  warp-config: